version: '3.9'

services:

  keycloak:
    container_name: keycloak
    image: ghcr.io/wolpertingers/hidden-keycloak:1.1.0
    network_mode: host
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: start-dev --http-port 18080 --import-realm
    volumes:
      - /etc/localtime:/etc/localtime:ro

  postgres:
    container_name: postgres
    image: postgres:13
    network_mode: host
    environment:
      POSTGRES_DB: forms
      POSTGRES_USER: wolpi
      POSTGRES_PASSWORD: secret

  hidden-forms:
    container_name: hidden-forms
    build: .
    profiles:
      - dockerized
    network_mode: host
    environment:
      HTTP_PORT: 8081
