wolpertinger:
  config:
    path: "src/test/resources/config.json"
quarkus:
  oidc:
    auth-server-url: http://localhost:18080/realms/wolpertingers
    client-id: hidden-forms
    application-type: web-app
    authentication:
      redirect-path: /
      restore-path-after-redirect: true
      user-info-required: true
    token-state-manager:
      split-tokens: true
    logout:
      path: /logout
      post-logout-path: /
  http:
    proxy:
      proxy-address-forwarding: true
    auth:
      permission:
        ui:
          paths: /
          policy: authenticated
