wolpertinger:
  config:
    path: "src/test/resources/config.json"
quarkus:
  oidc:
    auth-server-url: http://localhost:18080/realms/wolpertingers
    client-id: hidden-forms
    application-type: web-app
    logout:
      path: /logout
      post-logout-path: /
  http:
    auth:
      permission:
        protected:
          paths: /
          policy: authenticated
