quarkus:
  datasource:
    db-kind: postgresql
    username: wolpi
    password: secret
    jdbc:
      url: jdbc:postgresql://localhost:5432/forms
  hibernate-orm:
    database:
      generation: drop-and-create # TODO: replace in prod

wolpertinger:
  config:
    path: "src/test/resources/config.json"
